title: Blog - argentenergy
description: Vulnerabilities discovered and exploited during my career.
url: "https://argentenergy.github.io/"
baseurl: ""
permalink: ":title/"

social-bluesky: argentenergy.bsky.social
social-github: argentenergy
social-linkedin: colinamcqueen

author: argentenergy
author-img: argentenergy.avif
