title: Blog - argentenergy
description: Vulnerabilities discovered and exploited during my career.
url: "https://argentenergy.github.io/"
baseurl: ""
permalink: ":title/"

social-bluesky: argentenergy.bsky.social
social-github: argentenergy
social-linkedin: colinamcqueen
social-bugcrowd: argentenergy

author: argentenergy
author-img: colin.avif
about-author: "With 12 years of IT experience – six as a developer and six in application security – I have successfully discovered and reported numerous vulnerabilities for customers and bug bounty programs.\n\nAuthor of the following CVEs: CVE-2021-36156 and CVE-2021-36157"

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"
